version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".gitignore",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*sysusers.conf",
    "*.tmpfiles",
    "*tmpfiles.conf",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
    "query-devices.cpp",
    "build-query-devices.sh",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "010-openvino-change-install-paths.patch",
    "020-openvino-disable-werror.patch",
    "030-openvino-ignore-system-onnx.patch",
    "040-openvino-opencv5-fix.patch",
]
SPDX-FileCopyrightText = "openvino contributors"
SPDX-License-Identifier = "Apache-2.0"
