version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "fix-thrust-api.patch",
    "onnxruntime-install-orttraining-files.patch",
    "onnxruntime-system-dnnl.patch",
    "onnxruntime-system-flatbuffers.patch",
    "onnxruntime-remove-pkg_resources.patch",
    "use-system-boost-mp11.patch",
    "onnxruntime-cuda-softmax-stream.patch",
    "onnxruntime-drop-sharded-moe.patch",
]
SPDX-FileCopyrightText = "onnxruntime contributors"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["onnxruntime-cutlass-4.4.2.patch"]
SPDX-FileCopyrightText = "NVIDIA CUTLASS contributors"
SPDX-License-Identifier = "BSD-3-Clause"
