version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "rocksdb-enable-tests.patch",
    "rocksdb-build-static-option.patch",
    "rocksdb-system-liburing.patch",
]
SPDX-FileCopyrightText = "rocksdb contributors"
SPDX-License-Identifier = "0BSD"
