version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "conditionally-define-closefrom.patch",
]
SPDX-FileCopyrightText = "Free Software Foundation, Inc."
SPDX-License-Identifier = "GPL-2.0-only"

[[annotations]]
path = [
    "clean-includes.patch",
]
SPDX-FileCopyrightText = "Free Software Foundation, Inc."
SPDX-License-Identifier = "LGPL-2.1-only"
