version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
    "*.conf",
    "*.script",
    "list-collections",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "minted-python-3.14.patch",
    "texmf.cnf.patch",
    "texmfcnf.lua.patch",
    "minted-3.8.patch",
]
SPDX-FileCopyrightText = "texlive-texmf contributors"
SPDX-License-Identifier = "GPL-2.0-or-later"
