[containers]
log_driver = "journald"

[network]
# systemd >= 259 no longer supports iptables, so we switch from the implicit default on iptables to nftables:
# https://gitlab.archlinux.org/archlinux/packaging/packages/containers-common/-/issues/7
firewall_driver = "nftables"
